language: ruby

rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
  - 2.3.8
  - 2.2.6
  - 2.1.9

before_install:
- sudo apt-get update -yq && sudo apt-get install -y graphviz
- gem install bundler -v 1.14.4
